import { Router } from "express";
import { getAlltokencont } from "../../adminController/tokenController";
import { getAlltokenusage } from "../../adminController/tokenController";
import { verifyAdmin } from "../../middlewares/verifyAdmin";
export const tokenrouter = Router();

/**
 * @swagger
 * tags:
 *   name: AdminTokens
 *   description: Token analytics and usage tracking for admin dashboard
 */

/**
 * @swagger
 * /admin/alltokens:
 *   get:
 *     summary: Get all tokens generated by users
 *     description: Returns all tokens created for authentication, sessions, or API usage.
 *     tags: [AdminTokens]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: All tokens retrieved successfully
 *       401:
 *         description: Unauthorized — Admin token required
 *       500:
 *         description: Server error
*/
tokenrouter.get("/alltokens", verifyAdmin, getAlltokencont);

/**
 * @swagger
 * /admin/alltokenusage:
 *   get:
 *     summary: Get token usage statistics
 *     description: Returns analytics for token usage such as how many tokens were used, by whom, and when.
 *     tags: [AdminTokens]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: Token usage stats retrieved successfully
 *       401:
 *         description: Unauthorized — Admin token required
 *       500:
 *         description: Server error
 */
tokenrouter.get("/alltokenusage", verifyAdmin, getAlltokenusage);


